---  # Resolve Project Exporter configuration

app:
  loglevel: WARNING
  log_to_file: false
  logfile_path: R:/Resolve Project Backups/@logs

schedule:
  countdown_warning: 30 # Set to 0 for no countdown warning
  enabled_backup_music: true
  backup_music_path: files://Resolve/Resolve Project Backups/alert_scheduled_backup.mp3

backup:
  active_only: false # Override with CLI option '--archive-active-only'
  in_project_dir: true
  in_static_dir: false
  static_dir: files://Resolve/Resolve Project Backups 
