---  # Resolve Project Exporter configuration

app:
  loglevel: WARNING
  log_to_file: false
  logfile_path: R:/Resolve Project Backups/@logs

schedule:
  frequency_in_minutes: 30
  countdown_warning: 30 # Set to 0 for no countdown warning

server:
  ip: 127.0.0.1 # Although you can install the server on another machine, you may run into some quirks!
  port: 8000

backup:
  active_only: false # Override with CLI option '--archive-active-only'
  in_project_dir: true
  in_static_dir: false
  static_dir: files://Resolve/Resolve Project Backups 
